### PR TITLE
added some keybinding defenitons

### PR DESCRIPTION
**Pull request by ghost**
for dired, neotree and vterm

### CODE REVIEW

**Comment by niyumard** [comment]
Hi!
Thanks for the PR.
The only problem is that =SPC .= is not for dired but for find file, if you'd fix that I could merge your PR.
Thanks once again.

**Comment by ghost** [comment]
sure :)

**Comment by ghost** [comment]
> Hi! Thanks for the PR. The only problem is that =SPC .= is not for dired but for find file, if you'd fix that I could merge your PR. Thanks once again.

Done. :D

**Review by niyumard — APPROVED** [review]
Merged, thanks!

**Pull request merged**
